services:
  transmission:
    build:
      context: ./build
      dockerfile: Dockerfile
    container_name: transmission
    restart: always
    volumes:
      - ./config:/config
      - ./downloads:/downloads
      - ./watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    networks:
      - transmission
    logging:
      options:
        max-size: 100M

networks:
  transmission: