version: '3.5'
services:
  transmission:
    build:
      context: ./build
      dockerfile: Dockerfile
    container_name: transmission
    restart: always  
    ports:
      - 9091:9091      
    environment:
     - APP_UID=1000
     - APP_GID=1000
    volumes:
      - transmission-config:/var/lib/transmission/config
      - ./downloads:/var/lib/transmission/downloads
    networks:
      transmission:
    logging:
      options:
        max-size: 100M
    
volumes:
  transmission-config:

networks:
  transmission: