version: '3.5'
services:
  transmission:
    build:
      context: ./build
      dockerfile: Dockerfile
    container_name: transmission
    restart: always
    #entrypoint: "sleep 10000000"  
    ports:
      - 9091:9091 ## web-service
      - 51413:51413/udp ## transmission port
    volumes:
      - ./config:/var/lib/transmission/config
      - ./downloads:/var/lib/transmission/downloads
      - ./watch:/var/lib/transmission/watch
    user: 1000:1000      
    environment:
      - APP_USERNAME=transmission
      - APP_GROUPNAME=transmission
      - PUID=1000
      - PGID=1000
    networks:
      docker:
    logging:
      options:
        max-size: 100M
    
networks:
  docker: